"""empty message

Revision ID: 9e59b2378b29
Revises: 3abf15dcb568
Create Date: 2020-09-27 16:27:19.802340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e59b2378b29'
down_revision = '3abf15dcb568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('entry', 'entry_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry', 'entry_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
